Repository Breakthrough-Energy/PreREISE, pull requests merged in 2021-02, with the labels that each got.

#136 Add retry to noaa download and update rap demo notebook
  prereise/gather/request_util.py
  prereise/gather/winddata/rap/demo/rap_demo.ipynb
  prereise/gather/winddata/rap/noaa_api.py
Labels: data collection

#139 docs: add link to intallation and contribution guide
  README.md
Labels: documentation

#146 Update link in PR template
  .github/pull_request_template.md
Labels: documentation

#150 fix: set attribute on wrapped function so it actually works
  prereise/gather/request_util.py
  prereise/gather/tests/test_retry.py
Labels: bug
